### PR TITLE
v1.0.0 PR

### PR DESCRIPTION
**Pull request by NMNS93**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_arraybackup/6)

### CODE REVIEW

**Comment by NMNS93** [comment]
fix #3 and #4

**Review by natashapinto — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_arraybackup/6)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @aledj2, @andyb3, @Graeme-Smith, @natashapinto, and @NMNS93)

___
*[ua_scannerbackup.py, line 19 at r2](https://reviewable.io/reviews/moka-guys/dnanexus_arraybackup/6#-Lu2d6HB7RYuPy8P1xzv:-Lu2d6HB7RYuPy8P1xzw:bqu4v6z) ([raw file](https://github.com/moka-guys/dnanexus_arraybackup/blob/5518bf844050f96b6992d2bde5477a0d7ab8d46c/ua_scannerbackup.py#L19)):*
> ```Python
> import win32evtlogutil
> 
> VERSION = '1.0.0'
> ```

Just a suggestion- would it not be useful to add a Git version tag instead of hard coding?

**Review by NMNS93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_arraybackup/6)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @aledj2, @andyb3, @Graeme-Smith, and @natashapinto)

___
*[ua_scannerbackup.py, line 19 at r2](https://reviewable.io/reviews/moka-guys/dnanexus_arraybackup/6#-Lu2d6HB7RYuPy8P1xzv:-Lu7CC166nMxNfskUGL7:bt0k6p5) ([raw file](https://github.com/moka-guys/dnanexus_arraybackup/blob/5518bf844050f96b6992d2bde5477a0d7ab8d46c/ua_scannerbackup.py#L19)):*
<details><summary><i>Previously, natashapinto wrote…</i></summary><blockquote>

Just a suggestion- would it not be useful to add a Git version tag instead of hard coding?
</blockquote></details>

As this would usually be in a setup.py file, I've requested this to be kept alongside the git version tag so we can see the version in the file on the scanner PC

**Review by natashapinto — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_arraybackup/6)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @aledj2, @andyb3, @Graeme-Smith, and @natashapinto)

**Review by natashapinto — APPROVED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_arraybackup/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2, @andyb3, and @Graeme-Smith)

**Pull request merged**
