### PR TITLE
code modified to run on genapp server

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_arraybackup/7)

### CODE REVIEW

**Review by natashapinto — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_arraybackup/7)* status: all files reviewed, 1 unresolved discussion (waiting on @aledj2)

___
*[ua_scanner_backup.py, line 13 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_arraybackup/7#-MbML_OODsZqJv1N9mYm:-MbML_OODsZqJv1N9mYn:bqihtme) ([raw file](https://github.com/moka-guys/dnanexus_arraybackup/blob/d0bbb01b270f5b9e39aace2873eae5241a25a5f1/ua_scanner_backup.py#L13)):*
> ```Python
> import os
> import subprocess
> import config as config
> ```

any reason in importing something as the same name?

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_arraybackup/7)* status: all files reviewed, 1 unresolved discussion (waiting on @natashapinto)

___
*[ua_scanner_backup.py, line 13 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_arraybackup/7#-MbML_OODsZqJv1N9mYm:-MbMP-85-B34elnvz2cd:b-tczsuz) ([raw file](https://github.com/moka-guys/dnanexus_arraybackup/blob/d0bbb01b270f5b9e39aace2873eae5241a25a5f1/ua_scanner_backup.py#L13)):*
<details><summary><i>Previously, natashapinto wrote…</i></summary><blockquote>

any reason in importing something as the same name?
</blockquote></details>

nope, changed

**Review by natashapinto — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_arraybackup/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Review by natashapinto — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_arraybackup/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Pull request merged**
